objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Number_of_Items__c</fullName>
        <label>Number of Items</label>
        <summaryForeignKey>Quote_Item__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Quote_Price__c</fullName>
        <label>Total Quote Price</label>
        <summarizedField>Quote_Item__c.Price__c</summarizedField>
        <summaryForeignKey>Quote_Item__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Picture_URL__c</fullName>
        <label>Picture URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote_Item__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>QuoteItems</relationshipLabel>
        <relationshipName>QuoteItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>QuoteItems</relationshipLabel>
        <relationshipName>QuoteItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{000000}</displayFormat>
        <label>Quote Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QuoteItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QuoteController.cls
public with sharing class QuoteController {
    @AuraEnabled(Cacheable=true)
    public static Quote_Item__c[] getQuoteItems(Id opportunityId) {
        return [
            SELECT
                Id,
                Quantity__c,
                Price__c,
                Product__r.Name,
                Product__r.Price__c,
                Product__r.Picture_URL__c,
                Opportunity__r.Total_Quote_Price__c,
                Opportunity__r.Number_of_Items__c
            FROM Quote_Item__c
            WHERE Opportunity__c = :opportunityId
            WITH SECURITY_ENFORCED
        ];
    }
}