objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote_Item__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>QuoteItems</relationshipLabel>
        <relationshipName>QuoteItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{000000}</displayFormat>
        <label>Quote Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QuoteItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OpportunityTriggerTest.cls
@isTest
private class OpportunityTriggerTest {
    @isTest
    static void testsendReviewEmail() {
        
         Account Accnt = TestDataFactory.getAccount();
        
        insert Accnt;
        
        // Create test Opportunity record
        Opportunity opp = TestDataFactory.getOpportunity(Accnt.id);
        insert opp;
        
        
        
        // Create test Opportunity Line Items
        List<product__c> products = TestDataFactory.getproducts();
                    insert products;
        
        // Create test Opportunity Line Items
        List<quote_item__c> oppLineItems = TestDataFactory.getQuoteItems(opp,products);
                    insert oppLineItems;

      
        opp.StageName='Negotiation/Review';
        update opp;


    }
}