objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Availability__c</fullName>
        <label>Availability</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                    <label>Available</label>
                </value>
                <value>
                    <fullName>In Negotiation</fullName>
                </value>
                <value>
                    <fullName>Sold out</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picture_URL__c</fullName>
        <label>Picture URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Types_of_houses__c</fullName>
        <label>Types of houses</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Apartment</fullName>
                </value>
                <value>
                    <fullName>Penthouses</fullName>
                </value>
                <value>
                    <fullName>Bungalow</fullName>
                </value>
                <value>
                    <fullName>House with garden</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code__c</fullName>
        <label>Zip / Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote_Item__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>QuoteItems</relationshipLabel>
        <relationshipName>QuoteItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>QuoteItems</relationshipLabel>
        <relationshipName>QuoteItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{000000}</displayFormat>
        <label>Quote Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QuoteItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    
    
    public static Account getAccount() {
        String recordTypeId  = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId(); 
        Account acc = new Account(
            RecordTypeID=recordTypeId,
            FirstName= 'Test FName',
            LastName= 'Test LName',
            PersonEmail = 'test@yahoo.com');
        return acc;
    }
    
    
    public static Opportunity getOpportunity(Id accountId) {
        Opportunity opp = new Opportunity(Name='Test Opportunity', StageName='Prospecting', CloseDate=Date.today(), Amount=10000,Accountid = accountId);
        return opp;
    }
    
    public static List<product__c> getproducts() {
        List<product__c> products = new List<product__c>{
            new product__c(Availability__c='Available',Description__c='This apartment is in heart of Pankow with lots of sunlight',
                           Location__c='Pankow',Name='1 BHK in Pankow',Price__c=3500.0,Zip_Postal_Code__c='13187',
                           Types_of_houses__c='Apartment',
                           Picture_URL__c='https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'),
                
                
                new product__c(Availability__c='Available',Description__c='This apartment is in heart of Pankow with lots of sunlight',
                               Location__c='Pankow',Name='1 BHK in Pankow',Price__c=3500.0,Zip_Postal_Code__c='13187',
                               Types_of_houses__c='Apartment',
                               Picture_URL__c='https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1')
                };

                    return products;
    }
    
    
    public static List<quote_item__c> getQuoteItems(opportunity opp,list<Product__c> products) {
        // Create test Opportunity Line Items
        List<quote_item__c> quoteLineItems = new List<quote_item__c>{
            new quote_item__c(Opportunity__c=opp.Id,Product__c=products[0].id,Price__c=3500.0),
                new quote_item__c(Opportunity__c=opp.Id,Product__c=products[1].id,Price__c=3500.0)
                };
                    
                    return quoteLineItems;
    }
}